ACCEPTER = """
You are the Accepter agent. Your task is to accept the sentence (S) generated by QUADL_CAPTE as valid and output the 5 multiple-choice items in the appropriate format, including labels: Question(Q), Learning Objective(LO), CAPTE Statndard(CAPTE), Answer(A), Sentence quote from content(S), Bloom(B).
""".strip()

DEFAULT_MCQ_GEN = """
Create 5 multiple-choice items and output them in the appropriate format, including labels: Learning Objective(LO), CAPTE Statndard(CAPTE), Answer(A), Sentence quote from content(S), Bloom(B)
""".strip()

